apiVersion: v1
kind: Namespace
metadata:
  name: flask
  labels:
    webapp: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dep
  namespace: flask
  labels:
    webapp: flask
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      webapp: flask
  template:
    metadata:
      labels:
        webapp: flask
    spec:
      containers:
      - name: flask
        image: registry.example.com:5000/project/flask-hw
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-lb
  namespace: flask
  labels:
    webapp: flask
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  selector:
    webapp: flask
  # Uncomment for static IP
  #loadBalancerIP: xxx.xxx.xxx.xxx
